[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-session>=0.8.0",
    "flask>=3.1.0",
    "xhtml2pdf>=0.2.17",
    "flask-cors>=6.0.0",
]
